import date from "../src/date/index"

test("date.format", () => {
    expect(date.format.toHourStringFromMins(-100)).toBe("")
    expect(date.format.toHourStringFromMins(0)).toBe("0分钟")
    expect(date.format.toHourStringFromMins(30)).toBe("30分钟")
    expect(date.format.toHourStringFromMins(100)).toBe("1小时40分钟")
    expect(date.format.toHourStringFromMins(120)).toBe("2小时")

    const dt = new Date(2019, 2, 3, 10, 22, 33, 666)
    expect(date.format.format(dt)).toBe("2019-03-03")
    expect(date.format.format(dt, "yyyy-MM-dd hh:mm:ss:S")).toBe("2019-03-03 10:22:33:666")
    expect(date.format.format(dt, "yy")).toBe("19")
    expect(date.format.format(dt, "yyyy")).toBe("2019")
    expect(date.format.format(dt, "yyyyabc")).toBe("2019abc")
    expect(date.format.format(new Date("abc"))).toBe("")
})

test("date.convert", () => {
    const dt = date.convert.toEntity(new Date("2019/01/27 10:11:30:888"))
    expect(dt.year).toBe(2019)
    expect(dt.month).toBe(1)
    expect(dt.day).toBe(27)
    expect(dt.hour).toBe(10)
    expect(dt.min).toBe(11)
    expect(dt.second).toBe(30)
    expect(dt.millisecond).toBe(888)
    expect(dt.week).toBe(0)

    expect(date.convert.parse("")).toBeNull()
    expect(date.convert.parse("123")).toBeNull()
    expect(date.convert.parse("/Date(1441036800000)/")).toEqual(new Date(1441036800000))

    //耗时统计测试
    let counter = date.convert.toCounterEntity(-1)
    expect(counter.year).toBe(0)
    expect(counter.month).toBe(0)
    expect(counter.day).toBe(0)
    expect(counter.hour).toBe(0)
    expect(counter.min).toBe(0)
    expect(counter.second).toBe(0)
    expect(counter.millisecond).toBe(0)

    counter = date.convert.toCounterEntity(3 * 360 * 24 * 3600 * 1000)
    expect(counter.year).toBe(3)
    expect(counter.month).toBe(0)
    expect(counter.day).toBe(0)
    expect(counter.hour).toBe(0)
    expect(counter.min).toBe(0)
    expect(counter.second).toBe(0)
    expect(counter.millisecond).toBe(0)

    counter = date.convert.toCounterEntity(3 * 30 * 24 * 3600 * 1000)
    expect(counter.year).toBe(0)
    expect(counter.month).toBe(3)
    expect(counter.day).toBe(0)
    expect(counter.hour).toBe(0)
    expect(counter.min).toBe(0)
    expect(counter.second).toBe(0)
    expect(counter.millisecond).toBe(0)

    counter = date.convert.toCounterEntity(3 * 24 * 3600 * 1000)
    expect(counter.year).toBe(0)
    expect(counter.month).toBe(0)
    expect(counter.day).toBe(3)
    expect(counter.hour).toBe(0)
    expect(counter.min).toBe(0)
    expect(counter.second).toBe(0)
    expect(counter.millisecond).toBe(0)

    counter = date.convert.toCounterEntity(3 * 3600 * 1000)
    expect(counter.year).toBe(0)
    expect(counter.month).toBe(0)
    expect(counter.day).toBe(0)
    expect(counter.hour).toBe(3)
    expect(counter.min).toBe(0)
    expect(counter.second).toBe(0)
    expect(counter.millisecond).toBe(0)

    counter = date.convert.toCounterEntity(3 * 60 * 1000)
    expect(counter.year).toBe(0)
    expect(counter.month).toBe(0)
    expect(counter.day).toBe(0)
    expect(counter.hour).toBe(0)
    expect(counter.min).toBe(3)
    expect(counter.second).toBe(0)
    expect(counter.millisecond).toBe(0)

    counter = date.convert.toCounterEntity(3 * 1000)
    expect(counter.year).toBe(0)
    expect(counter.month).toBe(0)
    expect(counter.day).toBe(0)
    expect(counter.hour).toBe(0)
    expect(counter.min).toBe(0)
    expect(counter.second).toBe(3)
    expect(counter.millisecond).toBe(0)

    counter = date.convert.toCounterEntity(3)
    expect(counter.year).toBe(0)
    expect(counter.month).toBe(0)
    expect(counter.day).toBe(0)
    expect(counter.hour).toBe(0)
    expect(counter.min).toBe(0)
    expect(counter.second).toBe(0)
    expect(counter.millisecond).toBe(3)

    counter = date.convert.toCounterEntity(3 * 360 * 24 * 3600 * 1000 + 4 * 30 * 24 * 3600 * 1000 + 5 * 24 * 3600 * 1000 + 6 * 3600 * 1000 + 7 * 60 * 1000 + 8 * 1000 + 9)
    expect(counter.year).toBe(3)
    expect(counter.month).toBe(4)
    expect(counter.day).toBe(5)
    expect(counter.hour).toBe(6)
    expect(counter.min).toBe(7)
    expect(counter.second).toBe(8)
    expect(counter.millisecond).toBe(9)

    counter = date.convert.toCounterEntity(99 * 360 * 24 * 3600 * 1000 + 11 * 30 * 24 * 3600 * 1000 + 29 * 24 * 3600 * 1000 + 23 * 3600 * 1000 + 59 * 60 * 1000 + 59 * 1000 + 999)
    expect(counter.year).toBe(99)
    expect(counter.month).toBe(11)
    expect(counter.day).toBe(29)
    expect(counter.hour).toBe(23)
    expect(counter.min).toBe(59)
    expect(counter.second).toBe(59)
    expect(counter.millisecond).toBe(999)

})