import file from "../src/file/index"

test("file.path", () => {
    expect(file.path.getStandardPath("c:", true)).toBe("c:\\")
    expect(file.path.getStandardPath("c:/a/b", true)).toBe("c:\\a\\b\\")
    expect(file.path.getStandardPath("c:\\a/b/", true)).toBe("c:\\a\\b\\")
    expect(file.path.getStandardPath("c:\\a\\b", true)).toBe("c:\\a\\b\\")
    expect(file.path.getStandardPath("c:/a/b", false)).toBe("c:\\a\\b")
    expect(file.path.getStandardPath("c:\\a/b", false)).toBe("c:\\a\\b")
    expect(file.path.getStandardPath("c:\\a/b\\", false)).toBe("c:\\a\\b")
    expect(file.path.getStandardPath("\\\\pc", true)).toBe("\\\\pc\\")
    expect(file.path.getStandardPath("\\\\pc/a/b", true)).toBe("\\\\pc\\a\\b\\")
    expect(file.path.getStandardPath("\\\\pc/a/b", false)).toBe("\\\\pc\\a\\b")

    expect(file.path.getFileName("")).toBe("")
    expect(file.path.getFileName("c:\\1\\2\\3.txt")).toBe("3.txt")
    expect(file.path.getFileName("c:\\1\\2\\3.4.5.txt")).toBe("3.4.5.txt")
    expect(file.path.getFileName("c:\\1\\2\\3.txt/4.pdf")).toBe("4.pdf")
    expect(file.path.getFileName("c:\\1\\2\\3")).toBe("3")
    expect(file.path.getFileName("c:/1/2\\3")).toBe("3")
    expect(file.path.getFileName("c:\\1\\2\\")).toBe("2")
    expect(file.path.getFileName("c:\\1\\2\\.abc")).toBe(".abc")
    expect(file.path.getFileName("c:\\1\\2\\3.txt/")).toBe("3.txt")
    expect(file.path.getFileName("c:\\1")).toBe("1")
    expect(file.path.getFileName("\\\\pc\\1")).toBe("1")

    expect(file.path.getFileNameWithoutExt("")).toBe("")
    expect(file.path.getFileNameWithoutExt("c:\\1\\2\\3.txt")).toBe("3")
    expect(file.path.getFileNameWithoutExt("c:\\1\\2\\3.4.5.txt")).toBe("3.4.5")
    expect(file.path.getFileNameWithoutExt("c:\\1\\2\\3.txt/4.pdf")).toBe("4")
    expect(file.path.getFileNameWithoutExt("c:\\1\\2\\3")).toBe("3")
    expect(file.path.getFileNameWithoutExt("c:/1/2\\3")).toBe("3")
    expect(file.path.getFileNameWithoutExt("c:\\1\\2\\")).toBe("2")
    expect(file.path.getFileNameWithoutExt("c:\\1\\2\\.abc")).toBe("")
    expect(file.path.getFileNameWithoutExt("c:\\1\\2\\3.txt/")).toBe("3")

    expect(file.path.getExt("")).toBe("")
    expect(file.path.getExt("c:\\1\\2\\3.txt")).toBe(".txt")
    expect(file.path.getExt("c:\\1\\2\\3.txt/4.pdf")).toBe(".pdf")
    expect(file.path.getExt("c:\\1\\2\\3")).toBe("")
    expect(file.path.getExt("c:\\1\\2\\")).toBe("")
    expect(file.path.getExt("c:\\1\\2\\3.txt/")).toBe(".txt")
    expect(file.path.getExt("c:\\1\\2\\3.txt/.")).toBe(".")
    expect(file.path.getExt("c:\\1\\2\\.abc")).toBe(".abc")
    expect(file.path.getExt("c:\\1\\2\\3.txt/a.b.c.d")).toBe(".d")
    expect(file.path.getExt("c:\\1\\2\\3.txt/.....")).toBe(".")

    expect(file.path.getExtWithoutDot("")).toBe("")
    expect(file.path.getExtWithoutDot("c:\\1\\2\\3.txt")).toBe("txt")
    expect(file.path.getExtWithoutDot("c:\\1\\2\\3.txt/4.pdf")).toBe("pdf")
    expect(file.path.getExtWithoutDot("c:\\1\\2\\3")).toBe("")
    expect(file.path.getExtWithoutDot("c:\\1\\2\\")).toBe("")
    expect(file.path.getExtWithoutDot("c:\\1\\2\\3.txt/")).toBe("txt")
    expect(file.path.getExtWithoutDot("c:\\1\\2\\3.txt/.")).toBe("")
    expect(file.path.getExtWithoutDot("c:\\1\\2\\.abc")).toBe("abc")
    expect(file.path.getExtWithoutDot("c:\\1\\2\\3.txt/a.b.c.d")).toBe("d")
    expect(file.path.getExtWithoutDot("c:\\1\\2\\3.txt/.....")).toBe("")


    expect(file.path.isLocalDiskRootPath("")).toBeFalsy()
    expect(file.path.isLocalDiskRootPath("/")).toBeFalsy()
    expect(file.path.isLocalDiskRootPath("c:\\a")).toBeFalsy()
    expect(file.path.isLocalDiskRootPath("c:\\a\\b\\c")).toBeFalsy()
    expect(file.path.isLocalDiskRootPath("c:\\")).toBeTruthy()
    expect(file.path.isLocalDiskRootPath("c:")).toBeTruthy()
    expect(file.path.isLocalDiskRootPath("\\\\pc")).toBeTruthy()
    expect(file.path.isLocalDiskRootPath("\\\\pc/")).toBeTruthy()

    expect(file.path.getLocalPathDiskName("")).toBe("")
    expect(file.path.getLocalPathDiskName("a")).toBe("")
    expect(file.path.getLocalPathDiskName("c:")).toBe("c")
    expect(file.path.getLocalPathDiskName("x:\\a\\b\\c")).toBe("x")
    expect(file.path.getLocalPathDiskName("\\\\pc")).toBe("pc")
    expect(file.path.getLocalPathDiskName("\\\\pc\\a\\b/c")).toBe("pc")

    expect(file.path.getPathFolderName("", true)).toBe("")
    expect(file.path.getPathFolderName("c", true)).toBe("c")
    expect(file.path.getPathFolderName("c:", true)).toBe("c")
    expect(file.path.getPathFolderName("c:\\", true)).toBe("c")
    expect(file.path.getPathFolderName("c:\\a\\b", true)).toBe("b")
    expect(file.path.getPathFolderName("c:\\a", false)).toBe("c")
    expect(file.path.getPathFolderName("c:\\a\\b.docx", false)).toBe("a")
    expect(file.path.getPathFolderName("\\\\pc", true)).toBe("pc")
    expect(file.path.getPathFolderName("\\\\pc\\a", true)).toBe("a")
    expect(file.path.getPathFolderName("\\\\pc\\a", false)).toBe("pc")
    expect(file.path.getPathFolderName("\\\\pc/a/b/c/d.docx", false)).toBe("c")


    expect(file.path.isSystemRecyclePath("c:\\a\\")).toBeFalsy()
    expect(file.path.isSystemRecyclePath("c:\\$RECYCLE.BIN\\")).toBeTruthy()

    expect(file.path.isOfficeTempPath("c:\\~$a\\b")).toBeFalsy()
    expect(file.path.isOfficeTempPath("c:\\~$a\\")).toBeTruthy()
    expect(file.path.isOfficeTempPath("c:\\~$a.docx")).toBeTruthy()

    expect(file.path.convertPathToFileUrl("c:\\a\\b\\c.docx")).toBe("file://c:/a/b/c.docx")
})